apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-serv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node1
    spec:
      containers:
      - name: node-container
        image: alpine:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-config
        - secretRef:
            name: node-secret

